# -*- coding: utf-8 -*-
"""test_weak.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETH3n5U1YfFV7GB7YErCwRljqi6bEPCp
"""

"""Run from meanflow/: python test_weak.py. CPU mathematical and model checks."""
import unittest
from types import SimpleNamespace
from unittest.mock import patch
import numpy as np
import torch
from models.weak_loss import fourier_coefficients, u_statistic, experimental_loss
from models.meanflow import MeanFlow
from models.unet import SongUNet

torch.set_num_threads(2)


def settings(method="weak"):
    return SimpleNamespace(
        method=method, weak_features=8, weak_weight=1.0,
        weak_sigma_z=1.0, weak_sigma_r=1.0, weak_sigma_t=1.0,
        weak_fp64=False, diag_probability=0.25,
        ema_decay=0.999, ema_decays=[],
    )


class WeakChecks(unittest.TestCase):
    def test_matrix_value_and_gradient_match_all_distinct_pairs(self):
        torch.manual_seed(10)
        B, M, d = 5, 7, 3
        F = torch.randn(B, d, dtype=torch.float64, requires_grad=True)
        v = torch.randn(B, d, dtype=torch.float64)
        A, phi = torch.randn(2, B, M, dtype=torch.float64)
        loss = u_statistic(F, v, A, phi)
        h = A[:, :, None] * F[:, None, :] + phi[:, :, None] * v[:, None, :]
        direct = sum((h[i] * h[j]).sum() for i in range(B) for j in range(B) if i != j)
        direct = direct / (B * (B - 1) * M * d)
        torch.testing.assert_close(loss, direct, atol=1e-12, rtol=1e-12)
        g1 = torch.autograd.grad(loss, F, retain_graph=True)[0]
        g2 = torch.autograd.grad(direct, F)[0]
        torch.testing.assert_close(g1, g2, atol=1e-12, rtol=1e-12)

    def test_fourier_transport_derivative_by_finite_difference(self):
        torch.manual_seed(20)
        z, v = torch.randn(2, 4, 3, dtype=torch.float64)
        t = torch.full((4, 1), 0.7, dtype=torch.float64)
        r = torch.full((4, 1), 0.2, dtype=torch.float64)
        W = torch.randn(5, 3, dtype=torch.float64)
        b, c, phase = torch.randn(3, 5, dtype=torch.float64)
        A, _ = fourier_coefficients(z, v, t, r, W, b, c, phase)
        eps = 1e-6
        _, plus = fourier_coefficients(z + eps*v, v, t + eps, r, W, b, c, phase)
        _, minus = fourier_coefficients(z - eps*v, v, t - eps, r, W, b, c, phase)
        torch.testing.assert_close(A, (plus-minus)/(2*eps), atol=1e-8, rtol=1e-8)

    def test_true_constant_velocity_has_zero_weak_integral(self):
        # Independent quadrature checks signs, F=(t-r)u and upper boundary.
        q, weights = np.polynomial.legendre.leggauss(80)
        t = torch.tensor((q+1)/2, dtype=torch.float64).reshape(-1, 1)
        w = torch.tensor(weights/2, dtype=torch.float64).reshape(-1, 1)
        r = torch.zeros_like(t)
        v = torch.tensor([0.7, -0.2], dtype=torch.float64).expand(len(t), -1)
        z = torch.tensor([0.1, 0.3], dtype=torch.float64) + t*v
        F = t*v
        W = torch.tensor([[1.1, -0.8], [0.4, 1.4]], dtype=torch.float64)
        b = torch.tensor([0.3, -0.4], dtype=torch.float64)
        c = torch.tensor([0.8, 0.5], dtype=torch.float64)
        phase = torch.tensor([0.2, 1.1], dtype=torch.float64)
        A, phi = fourier_coefficients(z, v, t, r, W, b, c, phase)
        h = A[:,:,None]*F[:,None,:] + phi[:,:,None]*v[:,None,:]
        integral = (w[:,:,None]*h).sum(0)
        torch.testing.assert_close(integral, torch.zeros_like(integral), atol=1e-12, rtol=0)

    def test_negative_estimate_is_preserved(self):
        F = torch.tensor([[1.0], [-1.0]], requires_grad=True)
        loss = u_statistic(F, torch.zeros_like(F), torch.ones(2,1), torch.zeros(2,1))
        self.assertEqual(loss.item(), -1.0)

    def test_one_sample_rejected(self):
        with self.assertRaises(ValueError):
            u_statistic(torch.zeros(1,1), torch.zeros(1,1), torch.ones(1,1), torch.zeros(1,1))

    def test_bias_and_unbiasedness_with_known_distribution(self):
        # h~N(mu,C), so E[U]=||mu||²/d and E[mean²]=target+tr(C)/(B*d).
        torch.manual_seed(30)
        trials, B, d = 40000, 4, 2
        mu = torch.tensor([0.6, -0.4], dtype=torch.float64)
        h = mu + torch.randn(trials,B,d,dtype=torch.float64)
        estimates = (h.sum(1).square().sum(1)-h.square().sum((1,2)))/(B*(B-1)*d)
        target = mu.square().mean()
        error = (estimates.mean()-target).abs()
        self.assertLess(error.item(), 5*estimates.std().item()/(trials**0.5))
        naive = h.mean(1).square().mean(1).mean()
        self.assertAlmostEqual((naive-target).item(), 1/B, delta=0.015)

    def test_official_unet_loss_backward_and_sampling(self):
        config = dict(img_resolution=8, in_channels=3, out_channels=3,
                      model_channels=16, channel_mult=[1,1], num_blocks=1,
                      attn_resolutions=[4], dropout=0)
        for method in ["weak", "mf_control", "imf_diag"]:
            torch.manual_seed(40)
            model = MeanFlow(SongUNet, settings(method), config)
            x = torch.randn(4,3,8,8)
            optimizer = torch.optim.Adam(model.net.parameters(), lr=1e-4)
            if method == "weak":
                with patch("torch.func.jvp", side_effect=AssertionError("weak must not use JVP")):
                    loss = model.forward_with_loss(x, None)
            else:
                loss = model.forward_with_loss(x, None)
            self.assertTrue(torch.isfinite(loss).item())
            loss.backward()
            grads = [p.grad for p in model.net.parameters() if p.grad is not None]
            self.assertTrue(all(torch.isfinite(g).all() for g in grads))
            self.assertGreater(sum(g.abs().sum().item() for g in grads), 0)
            optimizer.step()
            model.update_ema()
            model.eval()
            with torch.no_grad():
                sample = model.sample((2,3,8,8), device="cpu")
            self.assertEqual(sample.shape, (2,3,8,8))
            self.assertTrue(torch.isfinite(sample).all())


if __name__ == "__main__":
    unittest.main(verbosity=2)