# -*- coding: utf-8 -*-
"""weak_loss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXFRcpclMciNBWjJUhl1RhHR1JCWAMd5
"""

"""Appendix D.43, D.55 and D.99; unconditional, uniform-triangle objective."""
import math
import torch


def sample_uniform_triangle(batch, device, dtype=torch.float32):
    # Sorting iid uniforms gives q(r,t)=2 on 0<r<t<1 (in exact arithmetic).
    pair = torch.rand(batch, 2, device=device, dtype=dtype)
    r = pair.min(dim=1).values
    t = pair.max(dim=1).values
    return t[:, None, None, None], r[:, None, None, None]


def fourier_coefficients(z, velocity, t, r, Wz, br, ct, phase):
    """Wz:[M,d], all other feature parameters:[M], shared across samples."""
    z = z.flatten(1)
    velocity = velocity.flatten(1)
    t, r = t.reshape(-1, 1), r.reshape(-1, 1)
    xi = z @ Wz.T + r * br + t * ct + phase
    phi = (1 - t) * xi.cos()
    A = -xi.cos() - (1 - t) * xi.sin() * (ct + velocity @ Wz.T)
    return A, phi


def u_statistic(F, velocity, A, phi):
    """Exact O(B M d) algebra, with no B x M x d intermediate or detach."""
    F, velocity = F.flatten(1), velocity.flatten(1)
    batch, dim = F.shape
    if batch < 2:
        raise ValueError("U statistic requires at least two independent samples")
    features = A.shape[1]
    S = A.T @ F + phi.T @ velocity
    F2 = F.square().sum(dim=1, keepdim=True)
    V2 = velocity.square().sum(dim=1, keepdim=True)
    FV = (F * velocity).sum(dim=1, keepdim=True)
    diagonal = (A.square() * F2 + phi.square() * V2 + 2 * A * phi * FV).sum()
    # Negative estimates are valid. Do not clamp, abs(), or detach diagonal.
    return (S.square().sum() - diagonal) / (batch * (batch - 1) * features * dim)


def random_fourier_loss(z, velocity, F, t, r, features=64,
                        sigma_z=1.0, sigma_r=1.0, sigma_t=1.0,
                        fp64=False):
    dtype = torch.float64 if fp64 else torch.float32
    z, velocity, F = z.to(dtype), velocity.to(dtype), F.to(dtype)
    t, r = t.to(dtype), r.to(dtype)
    dim = z[0].numel()
    with torch.no_grad():
        # Per-update resampling; independent of the batch data; shared in batch.
        Wz = torch.randn(features, dim, device=z.device, dtype=dtype) * (sigma_z / math.sqrt(dim))
        br = torch.randn(features, device=z.device, dtype=dtype) * sigma_r
        ct = torch.randn(features, device=z.device, dtype=dtype) * sigma_t
        phase = torch.rand(features, device=z.device, dtype=dtype) * (2 * math.pi)
        A, phi = fourier_coefficients(z, velocity, t, r, Wz, br, ct, phase)
    return u_statistic(F, velocity, A, phi)


def experimental_loss(net, x, args):
    """Controlled MF / diagonal iMF / weak losses, with ordinary unweighted MSE."""
    x = x.float()
    if args.method == "weak":
        t, r = sample_uniform_triangle(len(x), x.device)
        velocity = torch.randn_like(x) - x
        z = x + t * velocity
        u = net(z, (t.flatten(), (t - r).flatten()), None)
        F = (t - r) * u
        weak = random_fourier_loss(
            z, velocity, F, t, r, args.weak_features,
            args.weak_sigma_z, args.weak_sigma_r, args.weak_sigma_t,
            args.weak_fp64,
        )
        # Separate diagonal input. Uniform t here is a stated design choice.
        td = torch.rand_like(t)
        vd = torch.randn_like(x) - x
        zd = x + td * vd
        ud = net(zd, (td.flatten(), torch.zeros_like(td).flatten()), None)
        # Normalized diagonal loss = Appendix D.115 / d.
        diag = (ud - vd).square().mean()
        total = diag + args.weak_weight * weak
        logs = {"diag_mse": diag, "weak_u": weak, "weighted_weak": args.weak_weight * weak}
    else:
        t, r = sample_uniform_triangle(len(x), x.device)
        # Same controlled sampler for MF and diagonal iMF, plus diagonal mass.
        mask = torch.rand_like(t) < args.diag_probability
        r = torch.where(mask, t, r)
        velocity = torch.randn_like(x) - x
        z = x + t * velocity

        def u_func(zz, tt, rr):
            return net(zz, (tt.flatten(), (tt - rr).flatten()), None)

        u = u_func(z, t, r)
        with torch.no_grad():
            direction = velocity if args.method == "mf_control" else u_func(z, t, t)
            _, dudt = torch.func.jvp(
                u_func, (z, t, r),
                (direction, torch.ones_like(t), torch.zeros_like(r)),
            )
        target = (velocity - (t - r) * dudt).detach()
        total = (u - target).square().mean()
        logs = {"strong_mse": total}
    return total, {name: value.detach() for name, value in logs.items()}